name: Build & Deploy Docker Container (CI/CD)

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install nix
        uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      # testing is done inside nix. see nix/default.nix
      - name: Build nix image
        run: nix --extra-experimental-features 'flakes nix-command' build --option sandbox false .#dockerImage

      - name: Load nix image
        run: docker load < result

      - name: Set Docker tag
        id: docker_tag
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/master" ]]; then
              echo "tag=latest" >> $GITHUB_OUTPUT
          else
              SAFE_TAG=$(echo "${GITHUB_REF#refs/heads/}" | tr '/' '-')
              echo "tag=${SAFE_TAG}" >> $GITHUB_OUTPUT
          fi


      - name: Tag Docker image
        run: docker tag autismal:latest ${{ secrets.DOCKERHUBUSER }}/autismal:${{ steps.docker_tag.outputs.tag }}

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUBPASS }}" | docker login -u "${{ secrets.DOCKERHUBUSER }}" --password-stdin

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUBUSER }}/autismal:${{ steps.docker_tag.outputs.tag }}